### ISSUE TITLE
Some thinking about Function as parameter

### ISSUE THREAD

**Issue by lihsai0** [veactjs/veact#1]
https://github.com/veactjs/veact/blob/e6047c655f3263473cf577df6eaef16b07ead5a2/src/logger.ts#L25-L29

https://github.com/veactjs/veact/blob/e6047c655f3263473cf577df6eaef16b07ead5a2/src/logger.ts#L39-L43

Learned a lot from this repo. And have some thinking about here: Should it use `Parameters` and `ReturnType` in here ?

``` typescript
type AnyFn = (...args: any) => any

function callWithErrorHandling<F extends AnyFn>(
  fn: F,
  errorString: string,
  ...args: Parameters<F>
): ReturnType<F> {

```

``` typescript
function callWithAsyncErrorHandling<F extends AnyFn>(
  fn: F | F[],
  errorString: string,
  ...args: Parameters<F>
): any[] { // return type is still thinking in this line
```

Just note it. Can be closed anytime.

**Comment by surmon-china** [comment]
@lihsai0 

Anyway, you can use a more rigorous inference, but it will not reflect on a better result.

The reason is that these two functions are consumed internally in the library, and no matter what values the functions return, it doesn’t change anything inside, because the results will not be consumed internally.

Besides, loose constraints are required internally to ensure the versatility of your function.

In fact, the user interface has already overloaded with strict types.

(By the way, this code segment forks from the source code of vue.)

**Comment by lihsai0** [comment]
Learned more! I dwelled on the details... Thanks.
